name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and display stats
        run: |
          # Replace 'YOUR-USERNAME' with your GitHub username
          curl -sS https://github-readme-stats.vercel.app/api?username=YOUR-USERNAME&count_private=true&show_icons=true -H "Authorization: token ${{ secrets.GH_TOKEN }}"
