name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README.md
        uses: anuraghazra/github-readme-stats@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
