name: Update GitHub Stats

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          show_icons: true
          hide_title: true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update GitHub Stats'
          file_pattern: '**/README.md'
